version: '3.9'
services:
  server:
    container_name: 'tailstat'
    tty: true
    stdin_open: true
    image: 'tailstat:ubuntu22.04'
    build: '.'
    volumes:
      - '.:/var/tailstat/'
    ports:
      - 10000:10000
      - 10001:10001
    networks:
      - default
  dashboard_res:
    container_name: 'tailstat_dashboard_res'
    tty: true
    stdin_open: true
    image: 'node:18-alpine'
    volumes:
      - './dashboard/:/var/tailstat/dashboard/'
    networks:
      - default
networks:
  default: 
    name: 'tailstat_network'
