#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")";

# Setup TailStat python dev dependencies
pip install -r "$SCRIPT_DIR/../requirements_dev.txt"

echo -e "\nTailStat dev dependecies successfully installed!\n"
