#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")";

# Setup TailStat python dependencies
pip install -r "$SCRIPT_DIR/../requirements.txt"

# Setup TailStat nginx config
cp "$SCRIPT_DIR/../etc/tailstat.conf" /etc/
cp "$SCRIPT_DIR/../etc/nginx/sites-available/tailstat_api" /etc/nginx/sites-available/
cp "$SCRIPT_DIR/../etc/nginx/sites-available/tailstat_dashboard" /etc/nginx/sites-available/
if [ ! -f /etc/nginx/sites-enabled/tailstat_api ]; then
    ln -s /etc/nginx/sites-available/tailstat_api /etc/nginx/sites-enabled/
else
    rm /etc/nginx/sites-enabled/tailstat_api
fi
if [ ! -f /etc/nginx/sites-enabled/tailstat_dashboard ]; then
    ln -s /etc/nginx/sites-available/tailstat_dashboard /etc/nginx/sites-enabled/
else
    rm /etc/nginx/sites-enabled/tailstat_dashboard
fi
nginx -t
service nginx restart

echo -e "\nTailStat successfully installed!\n"
