#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")";

# Remove TailStat python dev dependencies
pip uninstall -y -r "$SCRIPT_DIR/../requirements_dev.txt"

echo -e "\nTailStat dev dependencies uninstalled.\n"
